// Build script — emits, for every page, four artifacts that together
// satisfy AVL's per-page discovery model (post-2f7b046):
//
//   1. dist/<page>.html               human page with head links + body link + page-specific badge
//   2. dist/<page>.agent              the AVL companion view itself
//   3. dist/headers/<page>.txt        mock HTTP response headers (Link header + manifest)
//   4. samples/                       checked-in copies of the above for code review
//
// Run: `npm run build`

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  generateStaticAgentViews,
  renderAgentViewLinkHeader,
} from "@frontier-infra/avl";

import homeAgent   from "./index.agent.js";
import aboutAgent  from "./about.agent.js";
import austinAgent from "./services/austin.agent.js";

import { renderHtmlPage } from "./html.js";

type Page = {
  /** Human URL — what an agent or browser GETs. */
  url: string;
  /** Output path for the HTML page (relative to outDir). */
  htmlPath: string;
  /** Output path for the headers sample (relative to outDir). */
  headersPath: string;
  /** AVL agent view module for this page. */
  view: Parameters<typeof generateStaticAgentViews>[0]["pages"][number]["view"];
  /** HTML <title>. */
  title: string;
  /** HTML body fragment. */
  body: string;
};

const PAGES: Page[] = [
  {
    url: "/",
    htmlPath: "index.html",
    headersPath: "headers/index.txt",
    view: homeAgent,
    title: "Lonestar Electric — Licensed Austin Electricians",
    body: `<h1>Lonestar Electric</h1>
<p>Licensed master electricians serving greater Austin, TX. 24/7 emergency response.</p>`,
  },
  {
    url: "/about-us",
    htmlPath: "about-us.html",
    headersPath: "headers/about-us.txt",
    view: aboutAgent,
    title: "About — Lonestar Electric",
    body: `<h1>About Lonestar Electric</h1>
<p>Family-owned and operated since 2004. Master-licensed, bonded, insured.</p>`,
  },
  {
    url: "/services/austin",
    htmlPath: "services/austin.html",
    headersPath: "headers/services-austin.txt",
    view: austinAgent,
    title: "Electrical Services in Austin, TX — Lonestar Electric",
    body: `<h1>Electrical services in Austin, TX</h1>
<p>20-minute average response downtown; 47-minute average for emergencies metro-wide.</p>`,
  },
];

const outDir = "dist";

const result = await generateStaticAgentViews({
  outDir,
  pages: PAGES.map((p) => ({ url: p.url, view: p.view })),
  // Optional: deterministic timestamp so re-running the build doesn't
  // produce a spurious diff in samples/.
  generatedAt: process.env.AVL_GENERATED_AT,
});

const htmlWritten: string[] = [];
const headersWritten: string[] = [];

for (const page of PAGES) {
  const html = renderHtmlPage({
    path: page.url,
    title: page.title,
    body: page.body,
  });
  const htmlOut = join(outDir, page.htmlPath);
  await mkdir(dirname(htmlOut), { recursive: true });
  await writeFile(htmlOut, html, "utf8");
  htmlWritten.push(htmlOut);

  const headers = renderHeadersSample(page.url);
  const headersOut = join(outDir, page.headersPath);
  await mkdir(dirname(headersOut), { recursive: true });
  await writeFile(headersOut, headers, "utf8");
  headersWritten.push(headersOut);
}

console.log(`Wrote ${result.written.length} agent view(s):`);
for (const p of result.written) console.log(`  ${p}`);
console.log(`Wrote ${htmlWritten.length} HTML page(s):`);
for (const p of htmlWritten) console.log(`  ${p}`);
console.log(`Wrote ${headersWritten.length} headers sample(s):`);
for (const p of headersWritten) console.log(`  ${p}`);

/**
 * Builds a mock HTTP/1.1 200 response showing the headers a real server
 * would emit for the human page. Real servers must set the Link header
 * server-side — these checked-in files are documentation, not artifacts
 * the AVL package itself produces.
 */
function renderHeadersSample(path: string): string {
  const link = renderAgentViewLinkHeader({ path });
  return [
    "HTTP/1.1 200 OK",
    "Content-Type: text/html; charset=utf-8",
    `Link: ${link}`,
    "",
    "# Generated by examples/marketing-site/src/build.ts using",
    "# renderAgentViewLinkHeader({ path: \"" + path + "\" }).",
    "#",
    "# Real servers must emit this Link header for fetcher-gated agents",
    "# (e.g. Anthropic web_fetch) that don't parse the response body.",
    "",
  ].join("\n");
}
