// Build script — emits, for every page, four artifacts that together
// satisfy AVL's per-page discovery model (post-2f7b046):
//
//   1. dist/<page>.html               human page with head links + body link + page-specific badge
//   2. dist/<page>.agent              the AVL companion view itself
//   3. dist/headers/<page>.txt        mock HTTP response headers (Link header + manifest)
//   4. samples/                       checked-in copies of the above for code review
//
// Run: `npm run build`

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";

import {
  generateStaticAgentViews,
  renderAgentViewLinkHeader,
} from "@frontier-infra/avl";

import product from "./product.agent.js";

import { renderHtmlPage } from "./html.js";

type Page = {
  /** Human URL — what an agent or browser GETs. */
  url: string;
  /** Output path for the HTML page (relative to outDir). */
  htmlPath: string;
  /** Output path for the headers sample (relative to outDir). */
  headersPath: string;
  /** AVL agent view module for this page. */
  view: Parameters<typeof generateStaticAgentViews>[0]["pages"][number]["view"];
  /** HTML <title>. */
  title: string;
  /** HTML body fragment. */
  body: string;
};

const PAGES: Page[] = [
  {
    url: "/product/kettle-17-ss",
    htmlPath: "product/kettle-17-ss.html",
    headersPath: "headers/product-kettle-17-ss.txt",
    view: product,
    title: "1.7L Stainless Electric Kettle — Ironpeak",
    body: `<h1>1.7L Electric Kettle — Stainless</h1>
<p><strong>Ironpeak</strong> · $49 · 1500W rapid boil · 3-year warranty</p>
<p>Best-selling stainless kettle in the 1.5-2L segment. 4.6&#9733; across 287 reviews; ships same-day from Austin, TX.</p>`,
  },
];

const outDir = "dist";

const result = await generateStaticAgentViews({
  outDir,
  pages: PAGES.map((p) => ({ url: p.url, view: p.view })),
  generatedAt: process.env.AVL_GENERATED_AT,
});

const htmlWritten: string[] = [];
const headersWritten: string[] = [];

for (const page of PAGES) {
  const html = renderHtmlPage({
    path: page.url,
    title: page.title,
    body: page.body,
  });
  const htmlOut = join(outDir, page.htmlPath);
  await mkdir(dirname(htmlOut), { recursive: true });
  await writeFile(htmlOut, html, "utf8");
  htmlWritten.push(htmlOut);

  const headers = renderHeadersSample(page.url);
  const headersOut = join(outDir, page.headersPath);
  await mkdir(dirname(headersOut), { recursive: true });
  await writeFile(headersOut, headers, "utf8");
  headersWritten.push(headersOut);
}

console.log(`Wrote ${result.written.length} agent view(s):`);
for (const p of result.written) console.log(`  ${p}`);
console.log(`Wrote ${htmlWritten.length} HTML page(s):`);
for (const p of htmlWritten) console.log(`  ${p}`);
console.log(`Wrote ${headersWritten.length} headers sample(s):`);
for (const p of headersWritten) console.log(`  ${p}`);

/**
 * Builds a mock HTTP/1.1 200 response showing the headers a real server
 * would emit for the human page. Real servers must set the Link header
 * server-side — these checked-in files are documentation, not artifacts
 * the AVL package itself produces.
 */
function renderHeadersSample(path: string): string {
  const link = renderAgentViewLinkHeader({ path });
  return [
    "HTTP/1.1 200 OK",
    "Content-Type: text/html; charset=utf-8",
    `Link: ${link}`,
    "",
    "# Generated by examples/product-page/src/build.ts using",
    "# renderAgentViewLinkHeader({ path: \"" + path + "\" }).",
    "#",
    "# Real servers must emit this Link header for fetcher-gated agents",
    "# (e.g. Anthropic web_fetch) that don't parse the response body.",
    "",
  ].join("\n");
}
